version: '3.1'
services:
  add_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.add
    ports:
      - "9000:9000"
  sub_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.sub
    ports:
      - "9001:9001"
  mul_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.mul
    ports: 
      - "9002:9002"
  div_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.div
    ports:
      - "9003:9003"
