export const KALK_ADD_SERVER = process.env.EXPO_PUBLIC_KALK_ADD_SERVER_PORT
export const KALK_SUB_SERVER = process.env.EXPO_PUBLIC_KALK_SUB_SERVER_PORT
export const KALK_MUL_SERVER = process.env.EXPO_PUBLIC_KALK_MUl_SERVER_PORT
export const KALK_DIV_SERVER = process.env.EXPO_PUBLIC_KALK_DIV_SERVER_PORT
