[package]
name = "data-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
eyre =  { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
actix-web = { workspace = true }
