name: kalk / build / e2e tests
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'app/**'
      - '.github/workflows/kalk.e2e.tests.yml'
jobs:
  build_ios:
    name: Install, Build, and e2e Testing (iOS)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 18.x
      #     cache: yarn
      #     cache-dependency-path: '**/yarn.lock'

      - name: Set LANG globally for subsequent steps
        run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Run the required services
        run: |
          docker-compose up -d
          docker ps

      - name: Check that the required services are up
        run: |
          echo "Checking whether services are up..."
          declare -a containers=("e2e-testing-demo-add_server-1" "e2e-testing-demo-sub_server-1" "e2e-testing-demo-mul_server-1" "e2e-testing-demo-div_server-1")

          for container in "${containers[@]}"
          do
            if ! docker ps --format '{{.Names}}' | grep -q "${container}"
            then
              echo "Service ${container} is not up. Aborting..."
              exit 1
            fi
          done

          echo "All services are up and ready."

      - name: Test services using curl
        run: |
          retries=0
          service_counter=0
          all_services_up=1
          declare -a services=(http://127.0.0.1:9000/exec http://127.0.0.1:9001/exec http://127.0.0.1:9002/exec http://127.0.0.1:9003/exec)

          while [[ $retries -lt 5 ]]
          do
            for service in "${services[@]}"
            do
              curl -X POST -H 'Content-Type: application/json' -d '{"x": 200, "y": 100}' $service &>/dev/null
              if [[ "$?" -eq 0 ]]
              then
                service_counter=$((service_counter + 1))
              fi
            done

            if [[ $service_counter -eq ${#services[@]} ]]
            then
              all_services_up=0
              break
            else
              service_counter=0
              retries=$((retries + 1))
              sleep 5
              echo "Services not ready yet. Retrying..."
              continue
            fi
          done

          if [[ $all_services_up -eq 0 ]]
          then
            echo "All services checked and ready."
          else
            echo "Services are not ready. Aborting..."
            exit 1
          fi

      # - name: Install detox cli
      #   run: npm install -g detox-cli

      # - name: Install applesimutils
      #   run: |
      #     brew tap wix/brew
      #     brew install applesimutils

      - name: Setup Project
        working-directory: app/packages/kalk
        run: bash -c "yarn setup"

      - name: Pod install for iOS
        working-directory: app/packages/kalk/ios
        run: npx pod-install

      - name: Detox build for iOS
        working-directory: app/packages/kalk
        run: bash -c "detox build -c ios.release" > /dev/null

      - name: Detox e2e tests for iOS
        working-directory: app/packages/kalk
        run: bash -c "NODE_OPTIONS='--max-old-space-size=4096' detox test --headless --loglevel fatal -c ios.release"

      - name: Shut down services
        run: docker-compose down